### ISSUE TITLE
Lambda diskspace full

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-era5#12]
every other run give a os.error (disk full).

```
{
  "errorMessage": "[Errno 28] No space left on device",
  "errorType": "OSError",
  "requestId": "ebd17ddf-8fa3-4f6c-b45d-77659c2262a4",
  "stackTrace": [
    "  File \"/var/task/handler/download_era5.py\", line 24, in lambda_handler\n    result.download(target=f.name)\n",
    "  File \"/var/task/cdsapi/api.py\", line 171, in download\n    return self._download(self.location, self.content_length, target)\n",
    "  File \"/var/task/cdsapi/api.py\", line 130, in _download\n    with open(target, mode) as f:\n"
  ]
}
```
1. Simply not enough space for a file? Why does it work somtimes?
2. Warm cache problem? doesn't "with temporaryfile" remove files?

**Comment by skymandr** [comment]
Weird. Warm cache seems probable. Not sure how quick teardown of temp is. Maybe it is left up to the OS to handle..?
Would simply increasing disk space to 1024 or similar solve this, or would that just push the issue ahead of us?
